// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHireAI.Backend.Data;

#nullable disable

namespace SmartHireAI.Backend.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120093142_AddAnalyticsQueryLogs")]
    partial class AddAnalyticsQueryLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartHireAI.Backend.Data.AnalyticsQueryLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("log_id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("company_name");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("float")
                        .HasColumnName("confidence_score");

                    b.Property<string>("DetectedIntent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("detected_intent");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("executed_at");

                    b.Property<int>("ExecutionTimeMs")
                        .HasColumnType("int")
                        .HasColumnName("execution_time_ms");

                    b.Property<string>("ExtractedSlotsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("extracted_slots");

                    b.Property<string>("NaturalLanguageQuery")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("natural_language_query");

                    b.Property<Guid>("RecruiterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recruiter_id");

                    b.Property<int>("RowCount")
                        .HasColumnType("int")
                        .HasColumnName("row_count");

                    b.Property<string>("SqlTemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sql_template_id");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("success");

                    b.HasKey("LogId");

                    b.ToTable("analytics_query_logs");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Applicant", b =>
                {
                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("applicant_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentRole")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("current_role");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_birth");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gender");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("PreferredRole")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("preferred_role");

                    b.Property<string>("PreferredWorkLocation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("preferred_location");

                    b.Property<string>("ResumeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("resume_url");

                    b.Property<string>("Skills")
                        .HasColumnType("longtext")
                        .HasColumnName("skills");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ApplicantId");

                    b.ToTable("applicants");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.ApplicationMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("message_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("application_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sender_role");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("subject");

                    b.HasKey("MessageId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("application_messages");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Education", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("education_id");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("applicant_id");

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("college_name");

                    b.Property<int>("CompletionYear")
                        .HasColumnType("int")
                        .HasColumnName("completion_year");

                    b.Property<string>("Degree")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("degree");

                    b.Property<string>("Grade")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("grade");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("specialization");

                    b.HasKey("EducationId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("education");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("message_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sender_id");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sender_role");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("char(36)")
                        .HasColumnName("thread_id");

                    b.HasKey("MessageId");

                    b.HasIndex("ThreadId");

                    b.ToTable("inbox_messages");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.InboxThread", b =>
                {
                    b.Property<Guid>("ThreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("thread_id");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("applicant_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_message_at");

                    b.Property<Guid>("RecruiterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("subject");

                    b.HasKey("ThreadId");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("inbox_threads");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobApplication", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("application_id");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("applicant_id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("applied_at");

                    b.Property<float>("AtsScore")
                        .HasColumnType("float")
                        .HasColumnName("ats_score");

                    b.Property<DateTime?>("HiredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("hired_at");

                    b.Property<DateTime?>("InterviewAcceptedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("interview_accepted_at");

                    b.Property<DateTime?>("InterviewDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("interview_date");

                    b.Property<int?>("InterviewDuration")
                        .HasColumnType("int")
                        .HasColumnName("interview_duration");

                    b.Property<string>("InterviewMode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("interview_mode");

                    b.Property<string>("InterviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("interview_notes");

                    b.Property<bool>("IsViewedByRecruiter")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_viewed_by_recruiter");

                    b.Property<Guid>("JobId")
                        .HasColumnType("char(36)")
                        .HasColumnName("job_id");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("meeting_link");

                    b.Property<string>("RoundId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("round_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("JobId");

                    b.ToTable("job_applications");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobDescription", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("job_id");

                    b.Property<bool>("AssessmentRequired")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("assessment_required");

                    b.Property<string>("AssessmentType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("assessment_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employment_type");

                    b.Property<int>("ExperienceMax")
                        .HasColumnType("int")
                        .HasColumnName("experience_max");

                    b.Property<int>("ExperienceMin")
                        .HasColumnType("int")
                        .HasColumnName("experience_min");

                    b.Property<int>("ExperienceRequired")
                        .HasColumnType("int")
                        .HasColumnName("experience_required");

                    b.Property<string>("GrowthOpportunities")
                        .HasColumnType("longtext")
                        .HasColumnName("growth_opportunities");

                    b.Property<string>("InterviewMode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("interview_mode");

                    b.Property<string>("InterviewRounds")
                        .HasColumnType("longtext")
                        .HasColumnName("interview_rounds");

                    b.Property<string>("KeyResponsibilities")
                        .HasColumnType("longtext")
                        .HasColumnName("key_responsibilities");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("LocationType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("location_type");

                    b.Property<int>("NumberOfOpenings")
                        .HasColumnType("int")
                        .HasColumnName("number_of_openings");

                    b.Property<string>("PerksAndBenefits")
                        .HasColumnType("longtext")
                        .HasColumnName("perks_benefits");

                    b.Property<string>("ProbableSalary")
                        .HasColumnType("longtext")
                        .HasColumnName("probable_salary");

                    b.Property<Guid>("RecruiterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("RequiredSkills")
                        .HasColumnType("longtext")
                        .HasColumnName("required_skills");

                    b.Property<string>("RoleOverview")
                        .HasColumnType("longtext")
                        .HasColumnName("role_overview");

                    b.Property<int>("SalaryMax")
                        .HasColumnType("int")
                        .HasColumnName("salary_max");

                    b.Property<int>("SalaryMin")
                        .HasColumnType("int")
                        .HasColumnName("salary_min");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Technologies")
                        .HasColumnType("longtext")
                        .HasColumnName("technologies");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("JobId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("job_descriptions");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobEmbedding", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("char(36)")
                        .HasColumnName("job_id");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("embedding");

                    b.HasKey("JobId");

                    b.ToTable("jd_embeddings");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobSkill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("skill_id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<Guid>("JobId")
                        .HasColumnType("char(36)")
                        .HasColumnName("job_id");

                    b.Property<string>("ProficiencyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("proficiency_level");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("skill_name");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("SkillId");

                    b.HasIndex("JobId");

                    b.ToTable("job_skills");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.MatchResult", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("match_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("char(36)")
                        .HasColumnName("job_id");

                    b.Property<float>("MatchScore")
                        .HasColumnType("float")
                        .HasColumnName("match_score");

                    b.Property<DateTime>("RankedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ranked_at");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("resume_id");

                    b.HasKey("MatchId");

                    b.HasIndex("JobId");

                    b.HasIndex("ResumeId");

                    b.ToTable("match_results");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("notification_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Recruiter", b =>
                {
                    b.Property<Guid>("RecruiterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("CompanyLogo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_logo");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanySize")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("company_size");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_website");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("designation");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("industry");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("RecruiterType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("recruiter_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("RecruiterId");

                    b.ToTable("recruiters");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Resume", b =>
                {
                    b.Property<Guid>("ResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("resume_id");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("applicant_id");

                    b.Property<DateTime>("ParsedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("parsed_at");

                    b.Property<int>("ResumeHealthScore")
                        .HasColumnType("int")
                        .HasColumnName("resume_health_score");

                    b.Property<string>("ResumeText")
                        .HasColumnType("longtext")
                        .HasColumnName("resume_text");

                    b.HasKey("ResumeId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("resumes");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.ResumeEmbedding", b =>
                {
                    b.Property<Guid>("ResumeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("resume_id");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("embedding");

                    b.HasKey("ResumeId");

                    b.ToTable("resume_embeddings");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.ResumeEntity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<float>("Confidence")
                        .HasColumnType("float")
                        .HasColumnName("confidence");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EntityValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("entity_value");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("resume_id");

                    b.HasKey("EntityId");

                    b.HasIndex("ResumeId");

                    b.ToTable("resume_entities");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("auth_provider");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("profile_image");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("verification_token");

                    b.Property<DateTime?>("VerificationTokenExpiry")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("verification_token_expiry");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.WorkExperience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("experience_id");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("applicant_id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Duration")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("duration");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role");

                    b.HasKey("ExperienceId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("work_experience");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Applicant", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.User", "User")
                        .WithOne("ApplicantProfile")
                        .HasForeignKey("SmartHireAI.Backend.Data.Applicant", "ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.ApplicationMessage", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.JobApplication", "JobApplication")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Education", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Applicant", "Applicant")
                        .WithMany("Education")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.InboxMessage", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.InboxThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.InboxThread", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHireAI.Backend.Data.JobApplication", "JobApplication")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHireAI.Backend.Data.Recruiter", "Recruiter")
                        .WithMany()
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("JobApplication");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobApplication", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHireAI.Backend.Data.JobDescription", "JobDescription")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("JobDescription");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobDescription", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Recruiter", "Recruiter")
                        .WithMany("JobDescriptions")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobEmbedding", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.JobDescription", "JobDescription")
                        .WithOne("Embedding")
                        .HasForeignKey("SmartHireAI.Backend.Data.JobEmbedding", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDescription");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobSkill", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.JobDescription", "JobDescription")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDescription");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.MatchResult", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.JobDescription", "JobDescription")
                        .WithMany("Matches")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHireAI.Backend.Data.Resume", "Resume")
                        .WithMany()
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDescription");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Notification", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Recruiter", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.User", "User")
                        .WithOne("RecruiterProfile")
                        .HasForeignKey("SmartHireAI.Backend.Data.Recruiter", "RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Resume", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Applicant", "Applicant")
                        .WithMany("Resumes")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.ResumeEmbedding", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Resume", "Resume")
                        .WithOne("Embedding")
                        .HasForeignKey("SmartHireAI.Backend.Data.ResumeEmbedding", "ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.ResumeEntity", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Resume", "Resume")
                        .WithMany("Entities")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.WorkExperience", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Applicant", "Applicant")
                        .WithMany("WorkExperience")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Applicant", b =>
                {
                    b.Navigation("Education");

                    b.Navigation("Resumes");

                    b.Navigation("WorkExperience");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.InboxThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobDescription", b =>
                {
                    b.Navigation("Embedding");

                    b.Navigation("JobSkills");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Recruiter", b =>
                {
                    b.Navigation("JobDescriptions");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Resume", b =>
                {
                    b.Navigation("Embedding");

                    b.Navigation("Entities");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.User", b =>
                {
                    b.Navigation("ApplicantProfile");

                    b.Navigation("RecruiterProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
