// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHireAI.Backend.Data;

#nullable disable

namespace SmartHireAI.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251225041251_AddATSAndRanking")]
    partial class AddATSAndRanking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartHireAI.Backend.Data.Applicant", b =>
                {
                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("applicant_id");

                    b.Property<string>("CollegeName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("college_name");

                    b.Property<int?>("CompletionYear")
                        .HasColumnType("int")
                        .HasColumnName("completion_year");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentRole")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("current_role");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<string>("Grade")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("grade");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ApplicantId");

                    b.ToTable("applicants");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobDescription", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("ExperienceRequired")
                        .HasColumnType("int")
                        .HasColumnName("experience_required");

                    b.Property<Guid>("RecruiterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("RequiredSkills")
                        .HasColumnType("longtext")
                        .HasColumnName("required_skills");

                    b.Property<int>("SalaryMax")
                        .HasColumnType("int")
                        .HasColumnName("salary_max");

                    b.Property<int>("SalaryMin")
                        .HasColumnType("int")
                        .HasColumnName("salary_min");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("JobId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("job_descriptions");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobEmbedding", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("char(36)")
                        .HasColumnName("job_id");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("embedding");

                    b.HasKey("JobId");

                    b.ToTable("jd_embeddings");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.MatchResult", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("match_id");

                    b.Property<float>("FinalRankingScore")
                        .HasColumnType("float")
                        .HasColumnName("final_ranking_score");

                    b.Property<Guid>("JobId")
                        .HasColumnType("char(36)")
                        .HasColumnName("job_id");

                    b.Property<float>("MatchScore")
                        .HasColumnType("float")
                        .HasColumnName("match_score");

                    b.Property<DateTime>("RankedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ranked_at");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("resume_id");

                    b.Property<string>("SuitabilityLabel")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("suitability_label");

                    b.HasKey("MatchId");

                    b.HasIndex("JobId");

                    b.HasIndex("ResumeId");

                    b.ToTable("match_results");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Recruiter", b =>
                {
                    b.Property<Guid>("RecruiterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("CompanyLogo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_logo");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("designation");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("RecruiterId");

                    b.ToTable("recruiters");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Resume", b =>
                {
                    b.Property<Guid>("ResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("resume_id");

                    b.Property<string>("ATSFeedback")
                        .HasColumnType("longtext")
                        .HasColumnName("ats_feedback");

                    b.Property<int>("ATSScore")
                        .HasColumnType("int")
                        .HasColumnName("ats_score");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("applicant_id");

                    b.Property<DateTime>("ParsedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("parsed_at");

                    b.Property<int>("ResumeHealthScore")
                        .HasColumnType("int")
                        .HasColumnName("resume_health_score");

                    b.Property<string>("ResumeText")
                        .HasColumnType("longtext")
                        .HasColumnName("resume_text");

                    b.HasKey("ResumeId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("resumes");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.ResumeEmbedding", b =>
                {
                    b.Property<Guid>("ResumeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("resume_id");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("embedding");

                    b.HasKey("ResumeId");

                    b.ToTable("resume_embeddings");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.ResumeEntity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<float>("Confidence")
                        .HasColumnType("float")
                        .HasColumnName("confidence");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EntityValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("entity_value");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("resume_id");

                    b.HasKey("EntityId");

                    b.HasIndex("ResumeId");

                    b.ToTable("resume_entities");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("profile_image");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Applicant", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.User", "User")
                        .WithOne("ApplicantProfile")
                        .HasForeignKey("SmartHireAI.Backend.Data.Applicant", "ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobDescription", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Recruiter", "Recruiter")
                        .WithMany("JobDescriptions")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobEmbedding", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.JobDescription", "JobDescription")
                        .WithOne("Embedding")
                        .HasForeignKey("SmartHireAI.Backend.Data.JobEmbedding", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDescription");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.MatchResult", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.JobDescription", "JobDescription")
                        .WithMany("Matches")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHireAI.Backend.Data.Resume", "Resume")
                        .WithMany()
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDescription");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Recruiter", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.User", "User")
                        .WithOne("RecruiterProfile")
                        .HasForeignKey("SmartHireAI.Backend.Data.Recruiter", "RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Resume", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Applicant", "Applicant")
                        .WithMany("Resumes")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.ResumeEmbedding", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Resume", "Resume")
                        .WithOne("Embedding")
                        .HasForeignKey("SmartHireAI.Backend.Data.ResumeEmbedding", "ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.ResumeEntity", b =>
                {
                    b.HasOne("SmartHireAI.Backend.Data.Resume", "Resume")
                        .WithMany("Entities")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Applicant", b =>
                {
                    b.Navigation("Resumes");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.JobDescription", b =>
                {
                    b.Navigation("Embedding");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Recruiter", b =>
                {
                    b.Navigation("JobDescriptions");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.Resume", b =>
                {
                    b.Navigation("Embedding");

                    b.Navigation("Entities");
                });

            modelBuilder.Entity("SmartHireAI.Backend.Data.User", b =>
                {
                    b.Navigation("ApplicantProfile");

                    b.Navigation("RecruiterProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
